// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mlsat.Services;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mlsat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240409111334_int")]
    partial class @int
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mlsat.Models.Entities.Columns.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.ToTable("Column");
                });

            modelBuilder.Entity("Mlsat.Models.Entities.DataSources.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseDataSourceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDstLoaded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoadAp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoadDst")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoadKp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoadWolf")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNaDropped")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNormalize")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("TimeColumn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseDataSourceId");

                    b.HasIndex("ProjectId");

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("Mlsat.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Mlsat.Models.Entities.Columns.Column", b =>
                {
                    b.HasOne("Mlsat.Models.Entities.DataSources.DataSource", null)
                        .WithMany("Columns")
                        .HasForeignKey("DataSourceId");
                });

            modelBuilder.Entity("Mlsat.Models.Entities.DataSources.DataSource", b =>
                {
                    b.HasOne("Mlsat.Models.Entities.DataSources.DataSource", "BaseDataSource")
                        .WithMany()
                        .HasForeignKey("BaseDataSourceId");

                    b.HasOne("Mlsat.Models.Project", "Project")
                        .WithMany("DataSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseDataSource");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Mlsat.Models.Entities.DataSources.DataSource", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Mlsat.Models.Project", b =>
                {
                    b.Navigation("DataSources");
                });
#pragma warning restore 612, 618
        }
    }
}
